### ISSUE TITLE
Error when executing "knit"

### ISSUE THREAD

**Issue by db-tech** [CWWhitney/BurkinaExample#1]
When executing knit on Burkina_vignette.Rmd, i get the following error:

```
Quitting from lines 1235-1237 (Burkina_vignette.Rmd) 
Error in file(file, "rt") : cannot open the connection
Calls: <Anonymous> ... eval -> eval -> kable -> read.csv -> read.table -> file
Execution halted
```

The problem seems to be that the file **MCResults/welfareDecisionSummary.csv** in line **1236** cannot be found.

https://github.com/CWWhitney/BurkinaExample/blob/ecd896537397d89cfd8c54198ba2e19d8b2411aa/Burkina_vignette.Rmd#L1236

Any idea what went wrong ?

**Comment by CWWhitney** [comment]
Thanks for running this @db-tech. Turns out that you will need to download the .csv file (6966KB) and place it in the folder 'MCResults' in your local repo. 

Here is the file on Dropbox: 

https://www.dropbox.com/s/3391ej27sqwei5h/welfareDecisionSummary.csv?dl=0
